# Site setting 
title: "Real Estate Document"
# subtitle: ""
description: ""
author: ""
theme: minima
copyright: "© 2025"
collaborators:
  - name: ""
  - name: ""
# Auther and collaborators 

# Other configurations
markdown: kramdown
# Optional: Set up navigation
header_pages:
  - README.md
